services:
  - type: web
    name: veast-shop-nsdh
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        value: VEAST_Order_Bot
      - key: PUBLIC_BASE_URL
        value: https://veast-shop-nsdh.onrender.com
      - key: SUPPORT_TELEGRAM_USERNAME
        value: veast_support
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_STATUS_KEY
        sync: false
      - key: CDEK_CLIENT_ID
        sync: false
      - key: CDEK_CLIENT_SECRET
        sync: false
      - key: CDEK_API_BASE_URL
        value: https://api.cdek.ru/v2
      - key: CDEK_FROM_CITY
        value: Москва
      - key: CDEK_DEFAULT_LOCATION
        value: Москва
